# this file uses prebuilt image in dockerhub
services:
  personal-website:
    image: amirpourmand/al-folio:slim
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
